theme: jekyll-theme-architect

title: [Sturdy-Happiness]
description: [A Trial Project]

show_downloads: false

links:
  download: https://glassfish.java.net/download.html
  mailinglist: https://java.net/projects/glassfish/lists/users/archive
  issuetracker: https://github.com/edbratt/sturdy-happiness/issues
  source: https://github.com/edbratt/sturdy-happiness
  license: https://github.com/edbratt/sturdy-happiness/blob/master/LICENSE.md
  contribute: https://github.com/edbratt/sturdy-happiness/blob/master/CONTRIBUTING
